USB_VID = 0x239A
USB_PID = 0x80F4
USB_PRODUCT = "Pico"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_PICODVI = 1
CIRCUITPY_USB_AUDIO = 1
CIRCUITPY_USB_HID = 0
CIRCUITPY_GAMEPAD = 0
CIRCUITPY_JOYSTICK_XINPUT = 0
